# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88912751f1ff3628b66f4799c6e0919325784ff84043f9794f1923e29dc58994ae8b6965894688f8f18868bfd0a576998dc9f7132a33fa36335ec044dc1f1cd1

test:
  secret_key_base: 5df3d01b6ad807daf20766a0dea46c0327f60adf207f136e25282f30c53dbaad8f78a10a7c368a06b5da1e9218c2f3de4d90d85511f5ba2f5c49b5b47e41d0c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
